### Get all TodoItems
GET http://localhost:8080/webapi/TodoItems

### Get a single TodoItem with an id of 1
GET http://localhost:8080/webapi/TodoItems/1

### Get a JWT Token for user DLEE using ldap
POST http://localhost:8080/webapi/jwt/ldapJsonLogin
Content-Type:application/json

{
  "username": "DLEE",
  "password": "Password2015"
}

### GET a JWT Token for user sales01 using database Jsonlogin
POST http://localhost:8080/webapi/jwt/jsonLogin
Content-Type:application/json

{
  "username": "sales01",
  "password": "Password2015"
}

### Post using token. Change tokenForUser01 to retrieved token above
# curl -i -X POST http://localhost:8080/dmit2015-security-microservices-demo-start/webapi/TodoItems
#    -d '{"name":"Finish DMIT2015 Assignment 1","complete":false}'
#    -H 'Authorization: Bearer tokenForUser01'
#    -H 'Content-Type:application/json'
POST http://localhost:8080/webapi/TodoItems
Authorization: Bearer eyJraWQiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYWxlczAxIiwidXBuIjoic2FsZXMwMSIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJTYWxlcyJdLCJqdGkiOiI4ZmVlZTUzNy1iMzJjLTRhNDAtOGIyMC04YjdjODlmY2NlNTYiLCJpYXQiOjE2NDk4NjUyNDEsImV4cCI6MTY0OTg3OTY0MX0.miemDhMOyb92KK3ptiswDQJe5GtJfMGzlH5KA9gJtWZHNNsex9-cRJ6Ajz1hRV5ZNJ4CXXm3SiAUbmqiaKHntU0WQXYOP-Q-7V7xyvnwTM4V3KLVgIZvT4H65Ae1E04qvwTKZUi4YdRozqlUtmOloYKmxJ9k2zQUb0kXkjf6JDYHuDBWBQtwupBY3vughkhalky97iZYXnaVTJ6iEU2sm8wPMrOQ_d6pjFAPSO1Z5ftC_ZHzkxqb11xV10lQVNQ-yExt7t2NM6cqwHV6VtESlZLWjfWbyETWPKOgKzwGrAVMgyqFYiJklR6u2D_yw17q59Fj249sEyCYpcuecII2fw
Content-Type: application/json

{
  "name": "Finish DMIT2015 Assignment 1",
  "complete": false
}

###



### POST a new TodoItem
POST http://localhost:8080/webapi/TodoItems
Content-Type: application/json

{"name":"Finish DMIT2015 Assignment 2", "complete":false}

### Get a single TodoItem with an id of 4
GET http://localhost:8080/webapi/TodoItems/4

### Update TodoItem with an id of 2 and change name and complete properties.
PUT http://localhost:8080/webapi/TodoItems/2
Content-Type: application/json

{
  "id": 2,
  "name": "Updated TodoItem 2",
  "complete": true,
  "version": 0
}

### Update TodoItem with an id of 4 and change name and complete properties.
PUT http://localhost:8080/webapi/TodoItems/4
Content-Type: application/json

{
  "id":4,
  "name":"Start assignment 2",
  "complete":false,
  "version":0
}

### Delete an TodoItem with an id of 2
DELETE http://localhost:8080/webapi/TodoItems/2

### Delete an TodoItem with an id of 4
DELETE http://localhost:8080/webapi/TodoItems/4